# Generated by Django 4.0 on 2021-12-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_image/sliders_image/'),
        ),
    ]
