# Generated by Django 4.0 on 2021-12-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0002_alter_slider_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_content',
            field=models.TextField(default=''),
        ),
    ]
