# Generated by Django 4.0 on 2021-12-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseproduct',
            name='course_product_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_image/course_product_image/'),
        ),
    ]
