# Generated by Django 4.0 on 2021-12-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='article_body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='article_title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='created',
        ),
    ]
