# Generated by Django 4.0 on 2021-12-26 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_about_us', models.TextField()),
                ('footer_telegram', models.CharField(max_length=120)),
                ('footer_insta', models.CharField(max_length=120)),
                ('footer_whats_app', models.CharField(max_length=120)),
                ('footer_phone', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
