# Generated by Django 4.0 on 2021-12-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['menu_order']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['menu_item_order']},
        ),
    ]
